services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: on-failure
    env_file: .env
    environment:
      DOMAIN_NAME:       ${DOMAIN_NAME}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER:          ${MARIADB_USER}
      MARIADB_PASSWORD:      ${MARIADB_USER_PASSWORD}
      MARIADB_DATABASE:      ${MARIADB_NAME}
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception-network

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: on-failure
    env_file: .env
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST:     mariadb
      WORDPRESS_DB_NAME:     ${MARIADB_NAME}
      WORDPRESS_DB_USER:     ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD: ${MARIADB_USER_PASSWORD}
      DOMAIN_NAME:           ${DOMAIN_NAME}
      WP_TITLE:              ${TITLE}
      WP_ADMIN_USER:         ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD:     ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL:        ${WP_ADMIN_EMAIL}
      WP_USER:               ${WP_USER}
      WP_USER_PASSWORD:      ${WP_USER_PASSWORD}
      WP_USER_EMAIL:         ${WP_USER_EMAIL}
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception-network

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: on-failure
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html/wordpress:ro
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    networks:
      - inception-network

networks:
  inception-network:
    name: inception
    driver: bridge

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
