version: '3'

networks:                   
  inception-network:
    driver: bridge

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ggaribot/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ggaribot/data/mariadb
      o: bind

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception-network
    depends_on:
      - wordpress
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception-network
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception-network
    env_file:
      - .env
    restart: always